package enumeration;



public enum LogType 
{
	DATA_TRIPLE, DATA_SUBJECT, DATA_CREATION, DATA_CONNECTION, 
	DATA_DEEP_CREATION, DATA_DEEP_CONNECTION, 
	ALGO_PROBLEM, ALGO_RECURSION, 
	ALGO_DEEP_EDGE, ALGO_DEEP_STATE;
}
